### ISSUE TITLE
We could do with a common eslint definition

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-shape#10]
One of the biggest differences between this project and d3fc is the `one-var` rule. It might also help to add an editorconfig file:

http://editorconfig.org

**Comment by chrisprice** [comment]
:+1: for the editor config.

Think the eslint is trickier though. This project makes more use of es2015
features. I would prefer the new code adopted a standard set of rules (very
fond of the redux style) and d3fc stays as is.

**Comment by ColinEberhardt** [comment]
see: https://github.com/ColinEberhardt/d3fc-package-archetype
