### ISSUE TITLE
Property accessors are broken

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-shape#11]
The property accessors have been written using arrow functions, which do not have their own `arguments` variable. As a result, they will always be executed in 'setter' mode.

See the following:

```
const barShape = fc_shape.bar;

const bar = barShape()
  .width(100);

console.log(bar.width());
```

http://codepen.io/anon/pen/bpgGEw?editors=0011

@alisd23 @chrisprice (mentioning because I know chris has notifications issues ;-)

**Comment by chrisprice** [comment]
Good spot. Currently we have -

```js
    bar.width = (_x) => {
        if (!arguments.length) {
            return width;
        }
        width = functor(_x);
        return bar;
    };
```

I propose -

```js
    bar.width = (...args) => {
        if (!args.length) {
            return width;
        }
        width = functor(args[0]);
        return bar;
    };
```

**Comment by ColinEberhardt** [comment]
LGTM
